### ISSUE TITLE
メソッド名をcorrect_userにした方が一般的です

### ISSUE THREAD

**Issue by norotime** [tabata1993/syumitier#13]
https://github.com/tabata1993/syumitier/blob/cfd48ce65ca57f23590427bd5ff449c3d8be5409/app/controllers/users_controller.rb#L68

@tabata1993 Railsチュートリアルが参考になりますよ〜。
https://railstutorial.jp/chapters/updating_and_deleting_users?version=4.2#code-correct_user_before_filter

**Comment by tabata1993** [comment]
correct_userに変更しました。
