### ISSUE TITLE
このコードは意味がありますか？

### ISSUE THREAD

**Issue by norotime** [tabata1993/syumitier#15]
https://github.com/tabata1993/syumitier/blob/cfd48ce65ca57f23590427bd5ff449c3d8be5409/app/views/sessions/new.html.erb#L1

**Comment by tabata1993** [comment]
syumitier/app/helpers/application_helper.rb
の中の、page_titleメソッドで所得され
タブの表示名をページごとに変化させるために使用されるので、意味があります。
